USE [master]
GO

/****** Object:  Database [Markdown]    Script Date: 6/11/2019 11:15:54 AM ******/
CREATE DATABASE [Markdown]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Markdown', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Markdown.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Markdown_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Markdown_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Markdown] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Markdown].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Markdown] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Markdown] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Markdown] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Markdown] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Markdown] SET ARITHABORT OFF 
GO

ALTER DATABASE [Markdown] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Markdown] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Markdown] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Markdown] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Markdown] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Markdown] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Markdown] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Markdown] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Markdown] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Markdown] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Markdown] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Markdown] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Markdown] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Markdown] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Markdown] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Markdown] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Markdown] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Markdown] SET RECOVERY FULL 
GO

ALTER DATABASE [Markdown] SET  MULTI_USER 
GO

ALTER DATABASE [Markdown] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Markdown] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Markdown] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Markdown] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Markdown] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Markdown] SET  READ_WRITE 
GO


